version: "3"
services:
  web:
    container_name: learn-to-code
    restart: always
    environment:
      spring_profiles_active: dev
    build: .
    ports:
      - "8080:8080"
    links:
      - db
  db:
    image: "postgres"
    container_name: "postgres_container"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=34273427
      - POSTGRES_DB=code
    ports:
      - "5433:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data/

volumes:
  my_dbdata: